Lke 2021 display count of results per category
Linkurious/linkurious-rest-client pull request #191
Opened 2020-11-12 12:54 UTC by mzorkany

2020-11-19 07:05 UTC, francescoinfante approved these changes
ok to merge

2020-11-19 07:09 UTC, francescoinfante requested changes

2020-11-19 07:09 UTC, francescoinfante commented on src/api/Search/types.ts
>    moreResults?: boolean;
you also need to add the itemTypeCountLimit to the configuration interfaces in the rest-client

2020-11-23 09:43 UTC, aminerhanemi commented
The PR should target develop.

2020-11-23 10:54 UTC, merged