LKE-6922 feat(space): Add create space API
Linkurious/linkurious-rest-client pull request #470
Opened 2022-08-04 09:29 UTC by aminerhanemi

2022-08-04 09:30 UTC, aminerhanemi commented on src/api/spaces/index.ts
> +      errors: [UNAUTHORIZED, FORBIDDEN, DATA_SOURCE_UNAVAILABLE, INVALID_PARAMETER],
Still need to check which errors are returned

2022-09-19 12:40 UTC, gmasclet requested changes
This looks good to me beside a few misc changes :ok_hand:

2022-09-19 13:28 UTC, aminerhanemi commented on src/api/spaces/index.ts
> +      errors: [UNAUTHORIZED, FORBIDDEN, DATA_SOURCE_UNAVAILABLE, INVALID_PARAMETER],
In which case the server should return INVALID_PARAMETER?

2022-09-19 13:29 UTC, aminerhanemi commented on src/api/spaces/index.ts
> +import {LkErrorKey} from '../../http/response';
I don't think it is needed in each file. the mention in the readme is enough. Maybe need to check with @enys .
I can add still add it

2022-09-19 14:17 UTC, gmasclet approved these changes

2022-09-20 15:37 UTC, merged