LKE-10245 User wants to delete node group rule
Linkurious/linkurious-rest-client pull request #667
Opened 2024-02-08 14:47 UTC by mzorkany

2024-02-08 15:51 UTC, davidrapin approved these changes
looking good!

2024-02-12 13:17 UTC, aminerhanemi requested changes

2024-02-12 13:17 UTC, aminerhanemi commented on src/api/nodeGrouping/types.ts
> +export interface DeleteNodeGroupingRuleParams extends Pick<NodeGroupingRule, 'id' | 'sourceKey'> {}
should extends IDataSourceParams

2024-02-12 14:05 UTC, mzorkany commented on src/api/nodeGrouping/types.ts
> +export interface DeleteNodeGroupingRuleParams extends Pick<NodeGroupingRule, 'id' | 'sourceKey'> {}
done

2024-02-12 16:28 UTC, merged